### 행렬에 대한 연산: 덧셈, 스칼라 곱셈, 곱셈

In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])

print(A+B)
print(3*B)

[[11 22]
 [33 44]]
[[ 30  60]
 [ 90 120]]


In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2, 1], [1, 2], [1, 1]])

np.dot(A, B)

array([[ 7,  8],
       [19, 20]])

In [4]:
import numpy as np

A = np.matrix([[1, 2, 3], [4, 5, 6]])
B = np.matrix([[2, 1], [1, 2], [1, 1]])

A*B

matrix([[ 7,  8],
        [19, 20]])

### 전치

In [8]:
import numpy as np

A = np.arange(1, 7).reshape(2, 3)
print(A)

A.transpose(1, 0)

A.T

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

# 특별한 행렬

### 단위 행렬

In [10]:
import numpy as np

A = np.matrix([[2, 4], [4, 2]])
I = np.matrix(np.eye(2))

print(A*I)
print(I*A)

[[2. 4.]
 [4. 2.]]
[[2. 4.]
 [4. 2.]]


### 역행렬

In [14]:
import numpy as np

A = np.matrix([[2, 1], [-6, 3]])
b = np.matrix([[3], [-27]])

print(A.I * b)

[[ 3.]
 [-3.]]


### 대각행렬

In [15]:
import numpy as np

D = np.matrix(np.eye(3) * np.array([2, 1, 4]))

print(D.I)
print(D.I * D)

[[0.5  0.   0.  ]
 [0.   1.   0.  ]
 [0.   0.   0.25]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
### 대칭 행렬

In [17]:
import numpy as np

A = np.matrix([[2, 4], [4, 2]])
X = np.matrix([[0.7071, -0.7071], [0.7071, 0.7071]])
D = X.I * A * X

print(D)

[[ 6.00000000e+00 -1.31223519e-16]
 [-8.59474028e-18 -2.00000000e+00]]
